name: build

on:
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for proper signature verification

  debian:
    needs: verify
    uses: ./.github/workflows/build-image.yml
    with:
      containerfile: Dockerfile
      image: "$GITHUB_REPOSITORY"
      tag: debian
      update-check: "apt-get update >/dev/null && apt-get upgrade -s | grep '^Inst' || true"
    secrets: inherit
